make the summarize functions work for periodic data
dsbbfinddx/shinyfind pull request #20
Opened 2022-02-04 18:04 UTC by benubah

This PR improves the existing `summarize_over_` functions to be able to summarize data with a `period` column. This is helpful for the TRACK CHANGE OVER TIME sub-app, where data is summarized `daily`, `monthly`, `quarterly` and `yearly` instead of a single date or date range. 

Usage:
```
data_grpd <- group_by_period(data_all, period = "quarterly") |>
  select(-name, -set) |>
  left_join(country_last_update_info, by = "unit") |>
  filter(!is.na(last_update))
  
   data_summarized_over_time <- summarize_over_time(data_grpd, by_period = TRUE)
  data_summarized_over_group <- summarize_over_group(data_summarized_over_time, "country", by_period = TRUE)

```

`group_by_period()` is an exported function from the `timeseries` module

2022-02-06 12:01 UTC, christophsax requested changes
Probably good enough. I guess we could do without `group_coditional()`. 

Perhaps also without the `by_period` argument: As soon as you have a `period` column, it indicates that you want to `group_by` it.

E.g., something like this:


```r
data_grouped <- 
  if ("period" %in% colnames(data_filtered)) {
    group_by(data_filtered, unit, period)
  } else {
    group_by(data_filtered, unit)
  }
  

data_grouped |> 
  summarize(....
```

That would be quite a bit easier to understand.

2022-02-07 06:01 UTC, benubah commented on R/summarize.R
> +# this function allows determining what variables to group by depending on a
THanks

2022-02-07 06:04 UTC, benubah commented
>  I guess we could do without group_conditional(). 

Should be resolved by https://github.com/dsbbfinddx/shinyfind/pull/20/commits/9914518bcd902b7a1e6d67e88ff86bc316e5a05b

2022-02-07 06:49 UTC, christophsax approved these changes
Great, Thanks!

2022-02-07 11:17 UTC, merged